# Generated by Django 2.2.10 on 2020-03-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='acm_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='nonacm_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='reward',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
