# Generated by Django 2.2.10 on 2020-03-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200401_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='acm_fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='nonacm_fees',
            field=models.IntegerField(null=True),
        ),
    ]
